# -*- coding: utf-8 -*-
"""Q2-Treasure.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_xluDTsUMfmX0TIYALK-wtwyUJ8tvhzE
"""

from google.colab import drive
drive.mount('/content/drive')

pip install Pillow

# Chapter 1: The Gatekeeper

from PIL import Image
import time

def modify_image(file_path):
    try:
        # Generate the number
        current_time = int(time.time())
        generated_number = (current_time % 100) + 50
        if generated_number % 2 == 0:
            generated_number += 10

        # Open an image and modify it
        img = Image.open(file_path)
        img = img.convert('RGB')  # Ensure it's in RGB format
        pixels = img.load()

        # Modify the pixels
        for i in range(img.width):
            for j in range(img.height):
                r, g, b = pixels[i, j]
                pixels[i, j] = ((r + generated_number) % 256,
                                (g + generated_number) % 256,
                                (b + generated_number) % 256)

        # Save the new image
        img.save('/content/drive/MyDrive/HIT137/chapter1out.png')

        # Calculate the sum of the red pixel values
        red_sum = sum(pixels[i, j][0] for i in range(img.width) for j in range(img.height))
        return red_sum
    except IOError:
        print("Error: The file could not be opened or found.")
    except Exception as e:
        print(f"An error occurred: {e}")

# Example usage
red_pixel_sum = modify_image('/content/drive/MyDrive/HIT137/chapter1.jpg')
print(red_pixel_sum)