# -*- coding: utf-8 -*-
"""Q2-Treasure.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_xluDTsUMfmX0TIYALK-wtwyUJ8tvhzE
"""

from google.colab import drive
drive.mount('/content/drive')

pip install Pillow

# Chapter 1: The Gatekeeper

from PIL import Image
import time

def modify_image(file_path):
    try:
        # Generate the number
        current_time = int(time.time())
        generated_number = (current_time % 100) + 50
        if generated_number % 2 == 0:
            generated_number += 10

        # Open an image and modify it
        img = Image.open(file_path)
        img = img.convert('RGB')  # Ensure it's in RGB format
        pixels = img.load()

        # Modify the pixels
        for i in range(img.width):
            for j in range(img.height):
                r, g, b = pixels[i, j]
                pixels[i, j] = ((r + generated_number) % 256,
                                (g + generated_number) % 256,
                                (b + generated_number) % 256)

        # Save the new image
        img.save('/content/drive/MyDrive/HIT137/chapter1out.png')

        # Calculate the sum of the red pixel values
        red_sum = sum(pixels[i, j][0] for i in range(img.width) for j in range(img.height))
        return red_sum
    except IOError:
        print("Error: The file could not be opened or found.")
    except Exception as e:
        print(f"An error occurred: {e}")

# Example usage
red_pixel_sum = modify_image('/content/drive/MyDrive/HIT137/chapter1.jpg')
print(red_pixel_sum)

# Chapter 2: The Chamber of Strings

def process_string(s):
    if len(s) < 16:
        raise ValueError("String must be at least 16 characters long")

    number_string = ''.join(filter(str.isdigit, s))
    letter_string = ''.join(filter(str.isalpha, s))

    if not number_string or not any(char.isupper() for char in letter_string):
        raise ValueError("String must contain both numbers and uppercase letters.")

    # Convert digits in number_string to their ASCII decimal values
    ascii_values = [str(ord(char)) for char in number_string]

    # Convert uppercase letters in letter_string to their ASCII decimal values
    ascii_uppercase = [str(ord(char)) for char in letter_string if char.isupper()]

    return ' '.join(ascii_values + ascii_uppercase)

# Example usage
try:
    s = "a12bc34d56ef78gh90iJ"
    result = process_string(s)
    print(result)
except Exception as e:
    print(e)